import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

export function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;

    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();

    // Strip surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (key) {
      env[key] = value;
    }
  }

  return env;
}

export function serializeEnvFile(env: Record<string, string>): string {
  const lines: string[] = [
    "# Generated by Beakcrypt CLI",
    `# ${new Date().toISOString()}`,
    "",
  ];

  const sorted = Object.entries(env).sort(([a], [b]) => a.localeCompare(b));

  for (const [key, value] of sorted) {
    // Quote values that contain spaces, #, or newlines
    if (/[\s#]/.test(value)) {
      lines.push(`${key}="${value}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

export async function readEnvFile(
  filePath: string,
): Promise<Record<string, string>> {
  if (!existsSync(filePath)) {
    return {};
  }
  const content = await readFile(filePath, "utf-8");
  return parseEnvFile(content);
}

export async function writeEnvFile(
  filePath: string,
  env: Record<string, string>,
): Promise<void> {
  await writeFile(filePath, serializeEnvFile(env));
}
